# Generated by Django 5.2.8 on 2025-12-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
