# Generated by Django 5.2.8 on 2025-12-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0002_alter_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobilte',
            field=models.CharField(default='7098536011', max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
