# Generated by Django 5.2.8 on 2025-12-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0003_person_mobilte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['created_at'], 'verbose_name': 'Human', 'verbose_name_plural': 'Humans'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='mobilte',
            new_name='mobile',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Human',
        ),
    ]
