# Generated by Django 5.2.8 on 2025-12-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0004_alter_person_options_rename_mobilte_person_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
