# Generated by Django 5.2.8 on 2025-12-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0005_rename_sex_person_gender_person_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
