# Generated by Django 5.2.8 on 2025-12-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0006_person_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
    ]
