# Generated by Django 5.2.8 on 2026-01-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0010_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['created_at'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
