# Generated by Django 5.2.8 on 2026-01-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0012_personaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personaddress',
            table='personaddress',
        ),
    ]
